### ISSUE TITLE
Request / Overwrite default cursor on (pure) buttons

### ISSUE THREAD

**Issue by adampasc** [porscheui/porsche-design-system-contribution#28]
**Scope**  
As a user of the new porsche design system, i would like to be able to override the cursor behaviour on buttons. This is not possible at the moment, because the inner button has a default cursor set. Eventhough buttons typically do not have a pointer, we would still like to have this ability for consistency reasons as currently all our buttons have pointers on them. Also, it would be nice to be able to set the color.

**Props**
Button Pure
- States: default, hover

**Comment by adampasc** [comment]
<img width="1335" alt="Bildschirmfoto 2019-12-17 um 13 04 23" src="https://user-images.githubusercontent.com/45289503/70999121-10cbb880-20d9-11ea-9597-d075cd813598.png">
Above is a scenario from one of our projects. Keep in mind that this would be achievable using either the icon or the link, too.

**Comment by marcelbertram** [comment]
Assumption: Users feel irritated because buttons don't indicate to be clickable without hand cursor.

**Comment by marcelbertram** [comment]
Buttons are now also have the pointer cursor like the link component. But it is not configurable
