### ISSUE TITLE
Request / Add inherit mode to for text sizes pure in Sketch

### ISSUE THREAD

**Issue by marcelbertram** [porscheui/porsche-design-system-contribution#29]
**Scope**  
Topic 1:
Within the text, button-pure and link-pure component custom sizes can be defined using the inherit mode if required for the context. On design side that is only possible by detaching from symbol. != conistency

Topic 2:
Currently the offered text sizing steps in sketch are quite big - especially for lower text sizes.
Small = 16px
Medium = 24px

**Notes**  
- Based on user feedback (frequent requirements for new sizes) either an "inherit" mode for sketch should be included, or new text sizes added.

**Tasks**
- [ ] Decide on solution and validate with requester (@dfhirth)
- [ ] Add docu for additional text sizes to storefront

**Comment by marcelbertram** [comment]
An additional inherit mode for text styles is not possible in Sketch. Please detach the symbol and modify the text size and icon size manually.

**Comment by dfhirth** [comment]
@marcelbertram …already detached in my process. Can you name me a size ratio for ICON-SIZE - TEXT-SIZE?

**Comment by dfhirth** [comment]
@marcelbertram had a quick talk with Anna and got what I needed.
