### ISSUE TITLE
Request / Add hide icon to Link Pure component

### ISSUE THREAD

**Issue by dfhirth** [porscheui/porsche-design-system-contribution#30]
**Scope**  
"Link Pure" Component – Integrating an Icon-Hide Property true/false.
Thanks for a feedback, thanks for your efforts! Daniel from Home & Navigation

**Notes**  
Our application has the requirement to display link elements without an icon and without a red underline (so the inText Link doesn't work).

Example screen "hn-1920-level2-Mehr": The link items listed under  "Porsche erleben", "Service & Zubehör" and "Unternehmen". 

Example screen "hn_768_level3-PorscheErleben": The link items listed under  "Porsche erleben"

**Props**
- Property Icon-Hide: true/false 

![hn-1920-level2-Mehr](https://user-images.githubusercontent.com/58986456/71012841-023ccb80-20f0-11ea-886c-79d43008dc9f.png)
![hn_768_level3-PorscheErleben](https://user-images.githubusercontent.com/58986456/71012842-023ccb80-20f0-11ea-8443-c4863c67cbaf.png)

**Comment by marcelbertram** [comment]
build solution using p-text and link functionality for that purpose
`<p-text tag="span"><a href="#">Link</a></p-text>`

**Comment by dfhirth** [comment]
@marcelbertram thanks for your efforts! I will handover this solution to my developers.
