### ISSUE TITLE
Request / Hide Icon in Button Pure Component

### ISSUE THREAD

**Issue by dfhirth** [porscheui/porsche-design-system-contribution#31]
**Scope**
"Button Pure" Component – Integrating an Icon-Hide Property true/false.
Thanks for a feedback, thanks for your efforts! Daniel from Home & Navigation

**Notes**
Our application has the requirement to use a button functionality to trigger actions in our navigation.

Example screen "hn-1920-level2-Mehr": "Mehr" item. 
Example screen "hn_768_level2-Mehr": "Porsche erleben", "Service & Zubehör" and "Unternehmen".

You find these files in the Abstract Design Collection https://share.goabstract.com/ea8156a9-54ba-417f-a575-7f11eda7babc? and as attached screenshots.

**Props**
Property Icon-Hide: true/false

![hn_768_level2-Mehr](https://user-images.githubusercontent.com/58986456/71014350-197cb880-20f2-11ea-8e11-e3ccdf0a6d13.png)
![hn-1920-level2-Mehr](https://user-images.githubusercontent.com/58986456/71014351-1a154f00-20f2-11ea-8ea5-8d72a439e179.png)

**Comment by marcelbertram** [comment]
build solution using wrapped p-text and icon with link functionality for that purpose

**Comment by dfhirth** [comment]
@marcelbertram thanks for your efforts!
