### ISSUE TITLE
Bug / Path in tachometer icon contains stroke color

### ISSUE THREAD

**Issue by niklaskappler** [porscheui/porsche-design-system-contribution#32]
**Description**  
The tachometer SVG icon delivered by CDN contains a path with a black stroke colour. By that using the icon in dark theme mode on different background colours than black will show a wrong coloured part of the icon. 

**To Reproduce**  
1. Go to 'https://icons.porsche.com/'
2. Select dark mode theme
3. Set a background colour to p-icon
4. Check 'tachometer' icon

**Expected behavior**  
See all paths in dark mode as white.

**Screenshots**  
![Bildschirmfoto 2020-03-17 um 01 05 14](https://user-images.githubusercontent.com/19165207/76809957-c8fa2180-67ec-11ea-898e-d335e3107882.png)

**Test Device (please complete the following information):**  
 - Device: desktop
 - OS: macOS Catalina 10.15.3 (19D76)
 - Browser chrome
 - Version  80.0.3987.132

**Comment by o-hook** [comment]
@niklaskappler Thanks for mentioning this bug! We will fix this soon!

**Comment by o-hook** [comment]
@niklaskappler Please retest the icon. We have fixed this issue and purged it on the CDN. Please verify that your local Cache is empty.

**Comment by niklaskappler** [comment]
@o-hook I can verify that is fixed. Thanks for the fast response!
