### ISSUE TITLE
Request / Remove case sensitivity from icons

### ISSUE THREAD

**Issue by Hetachi** [porscheui/porsche-design-system-contribution#33]
**Scope**  
Icons should not be case sensitive, making icons case sensitive add extra space for user error when content editors are able to write in their own icon names, taken from PDS icon list.

**Notes**  
![image](https://user-images.githubusercontent.com/7768612/79872019-eaeb5300-83ed-11ea-830d-833827171fa3.png)

```
<p-icon size="small" name="Broadcast" aria-label="Highway icon"></p-icon>
```

Above example does not work when name is taken directly from icon list. User has to perform extra action and has to figure out that icon name != icon id

**Comment by marcelbertram** [comment]
@Hetachi How critical do you rate this request

**Comment by Hetachi** [comment]
@marcelbertram We are planning to open platform estimated after around 4-6 weeks.  It is not a critical issue, treat it as a improvement to user experience.

**Comment by o-hook** [comment]
We are working currently on our icon handling (#631). WIth the next release this will be fixed automatically (if you are **not** working with Typescript). And we will update the Icon Platform to show only kebab-case icon namings (because this is our general file naming convention).

**Comment by marcelbertram** [comment]
**Porsche Design System Solution**
All Porsche Design System components only support kebab-case / param-case. To avoid distractions we will update the icons.porsche.com case in oder to set icon name = icon id

**Comment by o-hook** [comment]
Icons names on https://icons.porsche.com/ are now displayed in kebab-case format.
