### ISSUE TITLE
Request / Brand Icons by default should use their guideline color.

### ISSUE THREAD

**Issue by Hetachi** [porscheui/porsche-design-system-contribution#34]
**Scope**
Change the color for brand icons to use the default brand color. Would ensure that icons by default have correct color.

**Notes**  
- Would allow us to provide p-icon component directly to content editors.
- This would eliminate any extra code required to ensure correct color of the p-icon from component users.

**Props** (if relevant)  
- Name:  Icon
- Themes: standard + inverted

**Comment by marcelbertram** [comment]
Porsche Design System solution:
The icon color by default is black for light theme and white for dark theme. For social icons / social links we provide appropriate color variables that can be set manually. 

With the next release we will publish the link social component, that by default contains the brand color within the hover state for specific social platforms.
Preview: https://designsystem.porsche.com/issue/535/#/components/navigation/link-social#code
