### ISSUE TITLE
Warning findDOMNode deprecated

### ISSUE THREAD

**Issue by M-Wiemann** [porscheui/porsche-design-system-contribution#35]
Hello,

i'm using the "@porsche-design-system/components-react": "1.3.0"
There are warnings because the following function used deprecated method "findDOMNode"

Line:50
/@porsche-design-system/components-react/dist/esm/lib/react-component-lib/createComponent.js

and

Line:55
/@porsche-design-system/components-react/dist/cjs/lib/react-component-lib/createComponent.js

My React Version:
"react": "16.13.1"
"react-dom": "16.13.1"

**Comment by o-hook** [comment]
Seems to be a problem with Stencil DS plugins, see issue: https://github.com/ionic-team/stencil-ds-plugins/issues/37

**Comment by o-hook** [comment]
Hi @M-Wiemann , could you please update to Porsche Design System v1.4.x an check if this issue still exists? If that's the case you can also try our RC v1.5.0.rc-0 . Thanks!

**Comment by M-Wiemann** [comment]
Hello @o-hook 
an update to Version 1.4.0 solved this problem.
Thank you 🙏🏼
