### ISSUE TITLE
Request / Documentation: Select Vanillia JS/Angular/React globally

### ISSUE THREAD

**Issue by mgansler** [porscheui/porsche-design-system-contribution#36]
**Scope**  
Scope is the documentation: the code tab of the components.
Examples are provided for Vanilla JS, Angular and React. I have to select my "Framework" for each and every example while it is very likely that if I'm interested in React in one case, I will be in another case as well. If possible, please make the selection of my desired "Framework" global.
Thanks!

**Comment by marcelbertram** [comment]
part of the Q2 Backlog / low priority

**Comment by marcelbertram** [comment]
Fixed in designsystem.porsche.com
