### ISSUE TITLE
Request / Color for transparent blocking layer modal background

### ISSUE THREAD

**Issue by mixer2** [porscheui/porsche-design-system-contribution#38]
**Scope**  
For loaders and modals we need a transparent blocking layer to gray out the page. This color was available as `$layer-blocking-background-color` in the old ui-kit.  
The definition for the color (black/grey tone + transparency value) of the blocking layer is missing at the moment.

Also a generic official concept for z-index ranges would be nice. For example to ensure, that the overlay of the Home and Nav - Navigation is not conflicting with the blocking layer, etc.

**Notes**  
- https://designsystem.porsche.com/v0/core/?p=atoms-layer-blocking
- https://designsystem.porsche.com/v1/#/scss-utils/variables

**Comment by marcelbertram** [comment]
$layer-blocking-background-color will be part of Q2

z-index concept is not yet planned and will be part of components with z-index (modal, etc.) > End of 2020

**Comment by annakrohmer** [comment]
New definition: https://share.goabstract.com/7b2f3502-937a-4117-b350-3db1a526c8c7

**Comment by o-hook** [comment]
Will be part of the final utilities package as SCSS/JS variable.
