### ISSUE TITLE
Request / Deactivate or override hover and active behaviour for p-link-pure

### ISSUE THREAD

**Issue by tobiasbreit** [porscheui/porsche-design-system-contribution#39]
**Scope**  
For some cases we need the ability to deactivate or override the color change while hover/active the p-link-pure component. So additional properties for this component would be helpful to have more control.

For example we need something like this:

```
<p-link-pure hover-color="$p-color-theme-dark-default"></p-link-pure>"
<p-link-pure hover="false"></p-link-pure>

```
**Notes**  
[https://designsystem.porsche.com/v1/#/scss-utils/variables](https://designsystem.porsche.com/v1/#/scss-utils/variables)
[https://designsystem.porsche.com/v1/#/components/navigation/link-pure#design](https://designsystem.porsche.com/v1/#/components/navigation/link-pure#design)

**Comment by marcelbertram** [comment]
![image](https://user-images.githubusercontent.com/42934679/83238824-46e88a80-a197-11ea-8208-992da2cc1135.png)

Hypothesis: Red hovering of text affects the readability in a negative way

**Comment by tobiasbreit** [comment]
Is there any update or timeline available here?

**Comment by stephanschroeter** [comment]
We'll created an issue in our board and will work on it. For now we won't offer a configurable styling but improve the contrast and coloring of hover / active colors on dark background.
