### ISSUE TITLE
Request / Deliver font files in build package

### ISSUE THREAD

**Issue by tobiasbreit** [porscheui/porsche-design-system-contribution#41]
**Scope**  
Font files should be included in the PDS npm package instead of being pulled over CDN. At the moment the font files will be requested when a PDS component is used on the page. This could happen earlier and prevent the page from switching the font which can appear as a flashing or snapping effect.

**Comment by marcelbertram** [comment]
Fixed with V2 FOUC / FOUT font partials: https://designsystem.porsche.com/latest/#/performance/loading-behaviour
