### ISSUE TITLE
Grid offset does not go well in combination with grid direction

### ISSUE THREAD

**Issue by saschakreher** [porscheui/porsche-design-system-contribution#44]
**Description**  
When the grid direction is row-reverse, the offset of grid items is unaffected. If one uses an offset to make a gap between two p-grid-items, the gap gets lost when the direction is changed as the offset is always set to the left side of an element. 

**To Reproduce**  
```html
    <div>
    <p-grid direction="row-reverse">
      <p-grid-item size="6" style="border: 1px solid green">first item</p-grid-item>
      <p-grid-item size="5" offset="1" style="border: 1px solid red">second item with one offset column that should be between both items but is still on the left</p-grid-item>
    </p-grid>
    </div>
```

**Expected behavior**  
If the grid direction is "row-reverse" the offset is expeted to go along with the direction and to appear on the opposite side.

**Screenshots**  
![grid_offset_direction](https://user-images.githubusercontent.com/34915650/90041809-18744900-dcca-11ea-9aae-72689622d51e.jpg)

**Comment by saschakreher** [comment]
In addition I tried a negative value for the offset in cases when the direction is reversed. But negative values seem not supported.

**Comment by marcelbertram** [comment]
p-grid component will be deprecated nd replaced by a CSS grid / utilities solution
