### ISSUE TITLE
Bug / Text Field Password icon overlap

### ISSUE THREAD

**Issue by patrick-kiesel-tree-it** [porscheui/porsche-design-system-contribution#45]
If you type a long password in a password input field the show/hide icon gets covered

**To Reproduce**  
1.got to https://designsystem.porsche.com/v1/#/components/text-field#design
2. type a long password in the password text input field.

**Expected behavior**  
if i type in a long password in a password input field the show/hide icon doesn't get covered

**Screenshots**  
<img width="940" alt="Screenshot 2021-01-28 at 09 25 23" src="https://user-images.githubusercontent.com/58975838/106110473-0ccaf080-614b-11eb-8949-0a3f15aaca05.png">
**Description**

**Comment by marcelbertram** [comment]
Fixed in V2, but will be fixed in V1 as well
