### ISSUE TITLE
Request / slot for icons in p-text-field-wrapper

### ISSUE THREAD

**Issue by mhaegeleMHP** [porscheui/porsche-design-system-contribution#46]
**Scope**  
The option to add icons before/after the input element while using input type="text". 
This is needed for e.g. to add a 'x' icon to clear the input.

![Image 09 02 21 at 14 27](https://user-images.githubusercontent.com/60395476/107372359-9e404800-6ae5-11eb-8431-9b7fa185515d.jpg)

**Comment by mhaegeleMHP** [comment]
Feedback to Jannik Sommerfeld (PPN)

**Comment by marcelbertram** [comment]
Wont be supported:

Users expect to have actions if icons are displayed inside a form field. Icons for decorative purposes causes error clicks we want to avoid. Also in some inputs, e.g. type="value", it is possible to add pre-/suffixes for metrics. Others have native actions, e.g. password manager in safari or the date in chrome. For this cases, we risk unintended overlappings or have to reduce the space for the actual input heavily.
