### ISSUE TITLE
Bug / Loading spinner is too big (p-spinner) v2

### ISSUE THREAD

**Issue by humanshahinnia** [porscheui/porsche-design-system-contribution#47]
**Description**  
Spinner ist not shown with its default stylings when using Porsche Design System v2.
Error does not occur with V1

**To Reproduce**  
1. Go to https://preview-profile.porsche.com/myprofile/us/en_US/personal-data
2. Log-in with a Porsche ID 'manuel.haeberle@porsche.ag'
3. Scroll down to mobile or addresses, add a new mobile / address or choose a new country
4. See big loading indicator

**Expected behavior**  
Small loading indicator

**Screenshots**  
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/47107645/109001670-7fc17b80-76a5-11eb-9046-a0c7e51d98a4.png">
<img width="330" alt="image" src="https://user-images.githubusercontent.com/47107645/109002414-7ab0fc00-76a6-11eb-9709-1ef4c2cec4ac.png">

**Notes**
Please contact Dennis Scherer (Porsche ID Profile) on how to reproduce the bug because the team already downgraded to Porsche Design System v1 on their test page.

**Test Device (please complete the following information):**  
 - macOs / chrome (Version 88.0.4324.192 (Offizieller Build) (x86_64))

**Comment by marcelbertram** [comment]
fixed with 2.0.0-rc.5
