### ISSUE TITLE
Bug / Select wrapper breaks when no option has been selected

### ISSUE THREAD

**Issue by oschlegel** [porscheui/porsche-design-system-contribution#48]
**Description**  
Select wrapper breaks when new item is selected and NO item has been selected before. The problem occurs at [here](https://github.com/porscheui/porsche-design-system/blob/d8f4bbbdb31b7fc2edcec576eab021a849ac618c/packages/components/src/components/form/select-wrapper/select-wrapper.tsx#L499) because `this.select.selectedIndex` is -1.

**To Reproduce**  
1. Go to https://my.porsche-preview.com/core/de/de_DE/events/1dDIipHPynhr8ZLyqtecdG
2. Login with manuel.haeberle@porsche.ag
3. Click on "Teilnehmen"
4. Select a option from the dropdown select

**Expected behavior**  
Option of selection should be selectable even if not option has been selected before

**Comment by marcelbertram** [comment]
For selects where one option of a list has to be selected and the input can not be predefined an ‘<option value hidden=“true”></option> has to be included as the initial default
