### ISSUE TITLE
Contribution / p-content-wrapper basic needs box-sizing: border-box or width: unset

### ISSUE THREAD

**Issue by leifmarcus** [porscheui/porsche-design-system-contribution#49]
**Scope**  
On smaller screens (e. g. 1024px width) when using the p-content-wrapper (in Angular) with attribute `width="basic"` the content will be bigger than the screen, because of the `box-sizing` which is `content-box` by default. The base width of the `p-content-wrapper` is set to `100%`, so when adding a padding it will be bigger than the window width

**Notes** 
- if you would add `box-sizing: border-box` to `.p-content-wrapper` it should work as expected.
- alternatively you could add `width: unset` to `.p-content-wrapper--basic`

![image](https://user-images.githubusercontent.com/2342671/113844188-8529df80-9794-11eb-81bc-f7d6da3ab642.png)

**Props** (if relevant)  
- Name: width
- States: basic
- Themes: both

**Subtasks**  
no subtasks needed

**Comment by leifmarcus** [comment]
By The way, I'm working with the Design System V2

**Comment by SetupCoding** [comment]
Hey @leifmarcus ! Could you verify that this issue is still happening in the latest (2.0.0) stable release of the porsche design system? We added a `min-width` property to the content-wrapper, which might already have fixed your issue.

**Comment by leifmarcus** [comment]
Hey, currently I cannot reproduce the bug anymore. Might be solved with the final 2.0.0 version,
