### ISSUE TITLE
Bug / Property "subscribe" does not exist on type "EventEmitter<void>" in p-modal component

### ISSUE THREAD

**Issue by benjamincovcic1234** [porscheui/porsche-design-system-contribution#51]
**Description**  
@Porsche-design-system -> p-modal component event for close modal
(close)="handleCloseModal($event)"
https://designsystem.porsche.com/latest/#/components/modal#examples

**To Reproduce**  
Integrate p-modal component to angular application.
Bind function to close p-modal

See: https://github.com/myporsche/kyc-ui-widget/tree/PAY-1928-API-create-submerchant/projects/kyc-ui-widget/src/lib/modal

**Expected behavior**  
Application is compiled successfully

**Screenshots**  
![image](https://user-images.githubusercontent.com/79444931/114832106-65b33800-9dce-11eb-83d0-97627185f6ab.png)

**Test Device (please complete the following information):**  
 - Device: Macbook
 - OS: Catalina
 - Browser: Chrome

**Comment by denyo** [comment]
Hello @benjamincovcic1234,
can you please share a minimal example that reproduces the behavior?

**Comment by SetupCoding** [comment]
Hello @benjamincovcic1234 
It looks liek you are trying to mutate the `@Input open` variable inside the child and expect the parent to get notified. This is not possible.

Here is an example implementation using the `@Output` directive to communicate the closing event back to the parent component: 
`modal.component.ts`
```ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  template: `<p-modal heading="Upload identity document" [open]="open" (close)="closeModal($event)">
    <p-text size="small" weight="regular" class="margin-bottom-24"> Select document type:</p-text>
  </p-modal>`,
  // changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'app-modal',
})
export class ModalComponent {
  @Input() open: boolean;

  @Output()
  close = new EventEmitter<CustomEvent<void>>();

  public closeModal(event: CustomEvent<void>): void {
    this.close.emit(event);
  }
}

```

`collection.page.ts
`
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'collection-page',
  template: `
    <app-modal [open]="isModalOpen" (close)="handleModalClose($event)"></app-modal>
    <p-button (click)="openModal()">Open Modal</p-button>
  `,
})
export class CollectionPage {
  isModalOpen = false;

  openModal() {
    this.isModalOpen = true;
  }

  handleModalClose(ev: CustomEvent<void>) {
    console.log(ev);
    this.isModalOpen = false;
  }
}

```

**Comment by SetupCoding** [comment]
Hey @benjamincovcic1234 any feedback from your side? Did the implementation work in the above described way?

**Comment by benjamincovcic1234** [comment]
@SetupCoding Hey, I tried that also but still the same issue

**Comment by SetupCoding** [comment]
@benjamincovcic1234 can you share a minimal example for us to reproduce?

**Comment by marcelbertram** [comment]
Should work with provided implementation guideline
