### ISSUE TITLE
Bug / PDS Components not showing on Safari 12 

### ISSUE THREAD

**Issue by cnagadya** [porscheui/porsche-design-system-contribution#56]
**Description**  
PDS components do not render in Safari 12. For the global header, this implies that it indefinitely displays in loading phase (but still clickable) since we rely on the [marque](https://designsystem.porsche.com/latest/components/marque/examples) component getting fully loaded before hiding the skeletion

**To Reproduce**  
1. Visit any of the sites using PDS v2.3.0 in Safari 12, e.g [header test page](https://react.preview-nav.porsche.com/) or [PCOM Swiss](https://www.porsche.com/swiss/de/)

**Expected behavior**  
![image](https://user-images.githubusercontent.com/26176338/135062728-b9b730d8-71f5-474d-832a-bdaeebca4d2a.png)
![image](https://user-images.githubusercontent.com/26176338/135062793-4153c448-4bc8-4693-8274-ce7df2e51f3a.png)

**Screenshots**  
![image](https://user-images.githubusercontent.com/26176338/135059560-6f508ddd-5a76-40f0-8f25-b2804bcf65c0.png)

![image](https://user-images.githubusercontent.com/26176338/135059594-ce5a9837-eddc-46a0-8903-9917bc7cb938.png)

**Test Device (please complete the following information):**  
 - Any iOS device with Safari 12

**Comment by marcelbertram** [comment]
Fixed with 2.6.1: Prevent breaking entire Porsche Design System due to lacking support of ResizeObserver, however Accordion still requires it. Global Resize Observer alternative will be released soon.
