### ISSUE TITLE
Bug / Modal Close Button moves to the left if no heading is provided

### ISSUE THREAD

**Issue by F43nd1r** [porscheui/porsche-design-system-contribution#57]
**Description**  
The Modal close button should keep its position regardless of the presence of a heading. It moves to the left instead if no heading is provided.

**To Reproduce**  
1. Go to https://designsystem.porsche.com/v2/components/modal/examples#without-heading
2. Click on 'Open Modal'
3. See error

**Expected behavior**  
I would expect the modal close button to stay right-aligned regardless of the presence of a heading.

**Screenshots**  

![Screenshot 2022-01-10 at 12-00-58 Porsche Design System](https://user-images.githubusercontent.com/10252708/148755506-2b2e5774-d1da-4a5d-b826-91fef2bde93a.png)
![Screenshot 2022-01-10 at 12-01-24 Porsche Design System](https://user-images.githubusercontent.com/10252708/148755533-a97de449-e06d-48ca-a8d4-afc7fde62c5c.png)

**Test Device (please complete the following information):**  
 - Device: Desktop
 - OS: Windows
 - Browser: firefox, chrome
 - Version ff 95, chrome 97

Can also be seen at https://finder.porsche.com/us/en-US/details/porsche-718-cayman-s-preowned-1LKWXN by scrolling down to 'Optional Equipment' and clicking on an equipment item.

**Comment by SetupCoding** [comment]
Is fixed with the release of `2.9.0-beta.1`.
