### ISSUE TITLE
Bug / p-link pure component Hover behavior when having a slotted A element

### ISSUE THREAD

**Issue by leifmarcus** [porscheui/porsche-design-system-contribution#58]
**Description**  
When including the `p-link-pure` component with using a slotted `<a href="...">`, the hover style is not as expected. please see the attached video. This occurs when using the `@porsche-design-system/components-js` version 2.8.0

**Usage**
```html
<p-link-pure size="x-large">
  <a href="http://porsche.com">Some link title</a>
</p-link-pure>
```

**To Reproduce**  
1. implement a `<p-link-pure><a href=""></p-link-pure>` component into any page.
2. run the page in the browser
3. hover with the mouse pointer over the link

**Expected behavior**  
The hover effect should be the same when using the not slotted version of the component.

**Screenshots**  

**Test Device**  
 - Device: Macbook Pro
 - OS: Mac Osx 11.6.2
 - Browser Chrome
 - Version 99.0.4844.51 (latest)

### Video that shows the behavior
https://user-images.githubusercontent.com/2342671/157653455-403a43f7-e7a8-4c34-b328-3d866ec90806.mov

**Comment by marcelbertram** [comment]
Workaround implemented for buggy chrome version - will be removed once Chrome updates
