### ISSUE TITLE
Bug / P-Tabs-Bar active-index underline in wrong position

### ISSUE THREAD

**Issue by m-frehe** [porscheui/porsche-design-system-contribution#61]
**Description**  
We are using the p-tabs-bar for navigation purposes in our project.
But there is a problem with the active-tabs-index. Sometimes there is a rendering issue when the active-tab-index is set on load and the underline is not on the correct position.

**To Reproduce**  
1. Open a project page (You can get a link per PN if you want - it's a porsche internal project)
2. Refresh the site a few times
3. The underline of the p-tabs-bar is missing or in wrong position

**Expected behavior**  
The underline is under the correct text from active tab index.

**Screenshots**  
Correct:
![Correct](https://user-images.githubusercontent.com/107979035/174958820-8c26f978-fd2f-42e7-bcfe-068dac9f49e3.PNG)

Wrong (MS Edge)
![Problem](https://user-images.githubusercontent.com/107979035/174958849-8d13ecf1-e203-4537-a2d7-afedd94fbce8.PNG)

Wrong (Firefox)
![Problem 2](https://user-images.githubusercontent.com/107979035/174958865-bf38a2bf-6f9d-4628-ae0d-f8973699357f.PNG)

**Test Device (please complete the following information):**  
 - Device: Desktop
 - OS: Windows
 - Browser: Edge, Firefox
 - Version: Edge (101.0.1210.39) / Firefox (91.8.0esr)

**Comment by o-hook** [comment]
Hi @m-frehe ,
thanks for reporting. We will have a look at it and will come back to you shortly.

**Comment by SetupCoding** [comment]
@m-frehe Please provide a code snippet or reproduction example in one of our sample repositories: 

- https://github.com/porscheui/sample-integration-react
- https://github.com/porscheui/sample-integration-angular
- https://github.com/porscheui/sample-integration-vanillajs
- https://github.com/porscheui/sample-integration-nextjs

I could not reproduce this error on Edge (101.0.1210.39) / Firefox (91.8.0esr) in our storefront.

**Comment by SetupCoding** [comment]
@m-frehe Are you using the Porsche Design System in an Angular application?

**Comment by SetupCoding** [comment]
@m-frehe Could you please verify if the issue persists with the `2.15.0-beta.0` release of the Porsche Design System?

**Comment by m-frehe** [comment]
Created an example with vanillajs
https://github.com/m-frehe/sample-integration-vanillajs/tree/issue/61/P-Tabs-Bar_active-index

Problem: when the p-tabs-bar is inside a div with display=none then the underline is not correct rendered.
We used it with a loading div and switched block/none

Our Fix atm is to create a loading div with position:fixed instead and the content div is behind it ;)
